name: Automatisation des tests
on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Compilation
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          echo "Compilation terminée"

      - name: Test fonction add
        run: ./build/src/calculator add 10 5

      - name: Test fonction sub
        run: ./build/src/calculator sub 10 5

      - name: Test fonction mul
        run: ./build/src/calculator mul 10 5

      - name: Test fonction div
        run: ./build/src/calculator div 10 5

      - name: Test fonction car
        run: ./build/src/calculator car 5

      - name: Déploiement
        run: echo "Déploiement de la solution"
