name: Automatisation des tests
on: push

jobs:
  Compilation_et_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Compilation
        run: |
          mkdir -p smake
          cd smake
          smake  # Utilise smake pour compiler le projet

      - name: Upload du binaire
        uses: actions/upload-artifact@v4
        with:
          name: calculator-build
          path: smake/src/calculator

  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation_et_tests
    steps:
      - name: Download du binaire
        uses: actions/download-artifact@v4
        with:
          name: calculator-build
          path: smake/src

      - name: Test fonction add
        run: ./smake/src/calculator add 10 5

  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation_et_tests
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: calculator-build
          path: smake/src
      - run: ./smake/src/calculator sub 10 5

  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation_et_tests
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: calculator-build
          path: smake/src
      - run: ./smake/src/calculator mul 10 5

  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation_et_tests
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: calculator-build
          path: smake/src
      - run: ./smake/src/calculator div 10 5

  Test_Car:
    runs-on: ubuntu-latest
    needs: Compilation_et_tests
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: calculator-build
          path: smake/src
      - run: ./smake/src/calculator car 5

  Deploy:
    runs-on: ubuntu-latest
    needs: [Test_Add, Test_Sub, Test_Mul, Test_Div, Test_Car]
    steps:
      - name: Déploiement de la solution
        run: echo "Déploiement de la solution"
