name: Automatisation des tests
on: push

jobs:
  Compilation_et_Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Compilation
        run: |
          cmake .
          make
          echo "Fichiers compilés :"
          find . -type f -executable -name "calculator*"  # Vérifie où se trouve le binaire
          chmod +x src/calculator  # Mettre le binaire exécutable si nécessaire

      - name: Test addition
        run: |
          ./src/calculator add 10 5

      - name: Test soustraction
        run: |
          ./src/calculator sub 10 5

      - name: Test multiplication
        run: |
          ./src/calculator mul 10 5

      - name: Test division
        run: |
          ./src/calculator div 10 5

      - name: Test "car"
        run: |
          ./src/calculator car 5 || echo "Commande 'car' non supportée"
          
      - name: Déploiement
        run: echo "Déploiement de la solution"
