name: Automatisation des tests
on: push

jobs:
  Compilation_et_Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Installation des dépendances
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Compilation
        run: |
          # Créer un dossier temporaire pour la compilation
          mkdir -p build
          cd build
          cmake ..
          make

          # Vérifier que le binaire existe
          if [ -f "./calculator" ]; then
            EXE="./calculator"
          elif [ -f "../src/calculator" ]; then
            EXE="../src/calculator"
          else
            echo "Erreur : binaire calculator introuvable"
            exit 1
          fi

          # Afficher le binaire et rendre exécutable
          echo "Binaire trouvé : $EXE"
          chmod +x $EXE
          # Sauvegarder le chemin pour les tests
          echo "EXE_PATH=$EXE" >> $GITHUB_ENV
          # Lister les fichiers pour debug
          ls -R

      - name: Test addition
        run: |
          $EXE add 10 5

      - name: Test soustraction
        run: |
          $EXE sub 10 5

      - name: Test multiplication
        run: |
          $EXE mul 10 5

      - name: Test division
        run: |
          $EXE div 10 5

      - name: Test car
        run: |
          $EXE car 5 || echo "Commande 'car' non supportée"

      - name: Déploiement
        run: echo "Déploiement de la solution"
